export default {
    API: 'http://localhost:5555/api/',
    API_FOR_FILE: 'http://localhost:5555/',

    VIDEO_UPLOADED: 'VIDEO_UPLOADED',
    TIME_STAMPS_RESEVED: 'TIME_STAMPS_RESEVED',
    SEEK_VIDEO: 'SEEK_VIDEO',
    UPLOADING_STARTED: 'UPLOADING_STARTED',
    VIDEO_PROCESSED: 'VIDEO_PROCESSED',
    STAMPS_PROCESSED: 'STAMPS_PROCESSED',
    ALL_PROCESSED: 'ALL_PROCESSED',
    UPLOAD_PAGE_OPENED: 'UPLOAD_PAGE_OPENED',
    ON_ERROR: 'ON_ERROR'
};
