export default {
    API: 'http://localhost:5555',

    VIDEO_UPLOADED: 'VIDEO_UPLOADED',
    TIME_STAMPS_RESEVED: 'TIME_STAMPS_RESEVED',
    SEEK_VIDEO: 'SEEK_VIDEO',
    UPLOADING_STARTED: 'UPLOADING_STARTED'
};
